#!/usr/bin/bash

if [[ -z "$1" ]]; then
    echo "Usage: $0 <filename> [tags...]"
    exit 1
fi

FILE_PATH="$1"

if [[ "$FILE_PATH" != *.md ]]; then
    FILE_PATH="${FILE_PATH}.md"
fi

if [[ -e "$FILE_PATH" ]]; then
    echo "Error: File '$FILE_PATH' already exists!"
    exit 1
fi

FILENAME="$(basename "$FILE_PATH" .md)"

shift


date=$(date +"%Y-%m-%dT%H:%M:%S%z")
# Insert colon in timezone offset (required by many standards)
date=${date:0:22}:${date:22}

printf -- "---\ntitle: \"%s\"\ndate: %s\ndraft: false\n" \
    "$FILENAME" "$date" > "$FILE_PATH"

if [[ $# -gt 0 ]]; then
    printf "tags:\n" >> "$FILE_PATH"
    for tag in "$@"; do
        printf "  - %s\n" "$tag" >> "$FILE_PATH"
    done
fi

printf -- "---\n" >> "$FILE_PATH"

echo "Created: $FILE_PATH with tags: $*"

