#!/usr/bin/bash

set -e

if [[ -t 0 ]]; then
  [[ -n "$*" ]] || exit 1
  input="$*"
else
  read -r input
fi

sep="============================================="

echo "$sep"
echo "$input"
echo "$sep"

