#!/usr/bin/perl -T
use strict;
use warnings;
use File::Find;
use File::Basename;

sub indexDir {
    my ($filter) = @_;



    my $home = $ENV{HOME};  
    my $startDir = sprintf("%s/github.com/DnFreddie/Notes/content/posts/", $home);

    # Untaint the directory path
    if ( $startDir =~ m{^(/[\w\-/\.]+)$} ) {
        $startDir = $1;
    }
    else {
        die "Invalid directory path: $startDir";
    }

    unless ( -d $startDir ) {
        die "Directory $startDir does not exist or is not a directory.";
    }

    # Replace spaces in the filter for the search phase only
    my $search_filter = $filter;
    $search_filter =~ s/\s+/_/g;

    my @files;
    find(
        {
            wanted => sub {
                return if -d $_;

                # Untaint the file path before using it
                if ( $File::Find::name =~ m{^(.*)$} ) {
                    my $untainted_file = $1;
                    push @files, $untainted_file;
                }
            },
            no_chdir => 1
        },
        $startDir
    );

    my @mapArray;
    for my $file (@files) {
        my $file_name = File::Basename::basename($file);
        $file_name =~ s/\..*$//;

        my ($relative_path) = $file =~ m!(posts/.*)!;

        if ( !defined $relative_path ) {
            warn "Could not find 'posts/' in path: $file\n";
            next;
        }

        if ( $file_name =~ /$search_filter/i ) {
            # Only replace underscores with spaces in the output file name
            $file_name =~ s/_/ /g;

            push @mapArray,
              {
                name => $file_name,
                path => $relative_path
              };
        }
    }

    return @mapArray;
}

sub replace {
    my ($strings) = @_;

    my $new_path = "/Notes/" . $strings->{path};

    $new_path =~ s/\.md$//;

    return sprintf( '[%s](%s)', $strings->{name}, $new_path );
}

while ( my $line = <STDIN> ) {
    chomp $line;

    # Don't replace spaces globally in the line; keep the filter intact
    $line =~ s/\[(.*?)\]/ 
        my @matches = indexDir($1);  
        if (@matches) {
            replace($matches[0]);  
        } else {
            "[$1]";  
        } 
    /eg;

    print "$line\n";
}

