#!/usr/bin/env python3
import sys
import re

header_pattern = re.compile(r"^(#+)\s+(.+)$")
code_block_pattern = re.compile(r'^```\w*')
inline_code_pattern = re.compile(r'`([^`]+)`')
special_char_pattern = re.compile(r'[^a-z0-9-]')
code_block = False

def slugify(text):
    slug = text.lower()
    slug = '-'.join(slug.split())
    slug = special_char_pattern.sub('', slug)
    return slug

for line in sys.stdin:
    if code_block_pattern.match(line.strip()):
        code_block = not code_block
        continue
    
    if code_block:
        continue
        
    if line.startswith('#'):
        match = header_pattern.match(line.strip())
        if match:
            level, title = len(match.group(1)), match.group(2)
            title_clean = re.sub(inline_code_pattern, r'\1', title)
            base_slug = slugify(title_clean)
            indent = " " * 2 * (level - 1)
            print(f"{indent}* [{title_clean}](#{base_slug})")
