#!/usr/bin/env bash

declare -A venv_dict
venv_dir=~/env/pyVenv/

create_dict() {
  venv_dict=()

  for dir_path in "$venv_dir"/*/; do
    dir_name=$(basename "$dir_path")
    activate_path="$dir_path/bin/activate"

    if [[ -f "$activate_path" ]]; then
      venv_dict["$dir_name"]=$activate_path
    fi
  done

  echo "Found ${#venv_dict[@]} virtual environments."
}

create_venv() {
  local venv_name="$1"
  local venv_path="$venv_dir/$venv_name"

  if [[ -z "$venv_name" ]]; then
    echo "Error: No virtual environment name provided."
    exit 1
  fi

  if [[ -d "$venv_path" ]]; then
    echo "Error: Virtual environment '$venv_name' already exists."
    exit 1
  fi

  mkdir -p "$venv_path"
  python3 -m venv "$venv_path"

  if [[ $? -eq 0 ]]; then
    echo "Virtual environment '$venv_name' created at $venv_path"
  else
    echo "Error: Failed to create virtual environment '$venv_name'"
    exit 1
  fi
}
source_venv() {

  if [[ ${#venv_dict[@]} -eq 0 ]]; then
    echo "No virtual environments found. Please run 'create_dict' first."
    return
  fi

  venv_names=("${!venv_dict[@]}")

  selected_venv=$(printf '%s\n' "${venv_names[@]}" | fzf)

  if [[ -n "$selected_venv" ]]; then
    activate_path="${venv_dict[$selected_venv]}"

    if [[ -f "$activate_path" ]]; then

      source "$activate_path"
      bash

    else
      echo "Error: Activation script not found for virtual environment $selected_venv"
    fi
  else
    echo "No virtual environment selected."
  fi
}

main() {
  if [[ "$1" == "create" && -n "$2" ]]; then
    create_venv "$2"
    exit 0
  fi

  create_dict
  source_venv

}
set -e
main "$@"
